### ISSUE TITLE
Ignore Errors documentation for Ignore HTTPS certificate errors

### ISSUE THREAD

**Issue by clach04** [mwarning/trigger#16]
I'm experimenting with Trigger app from Android with a Python Flask script that can be deployed with https certs or over plain http.

 * It works fine over http
 * It only works over https if the ignore errors option is set

I'm using a self signed certificate and I install the cert onto my phone (successfully) but I have to enable ignore errors.

Do you have any documentation how this can be set to not ignore errors?

**Comment by moba** [comment]
The idea so far is that you run it behind a proper hostname and certificate, to allow flexible use and not require any specific application. You can for example simply put bookmarks in your browser, and the goal is to stay as compatible and simple as possible with whatever integrations people build. I mostly use a simple command-line `wget` command towards the endpoint, for example.

Since you will likely point the hostname at a local IP, you cannot use the Letsencrypt Letsencrypt HTTP-01 challenge. You can however get valid DV certificates elsewhere (i.e. buy them), or use the Letsencrypt DNS-01 challenge.

I think Moritz has thought about adding proper support for self-signed certificates, a kind of "trust on first use" where `trigger` stores the certificate it sees and warns when it changes. At the moment however, both known `trigger` deployments use valid certificates.

**Comment by clach04** [comment]
Thanks @moba - yeah the bookmark solution is currently the only thing I can think of - as I can save the self-signed cert in the browser. I'm trying to avoid exposing my endpoint to the internet.

Trust on first use in the app would be great. I'll keep my fingers crossed.

**Comment by moba** [comment]
Yes you definitely don't want to expose the endpoint on the Internet. In our use cases, we have lots of users, with lots of different platforms and devices, which is why "proper" certificates were the way to go. I understand that for smaller deployments you might prefer self-signed certs.

Personally, all my domains end up in the HSTS preload list, which means any service on any subdomain needs proper certificates; there is no way in the browser to skip/ignore that. I like it that way.

**Comment by mwarning** [comment]
To allow self signed certificates in a safe way would be great to have. But it depends on if I have time to implement it.

**Comment by mwarning** [comment]
@clach04 the current ignore option ignores all kind of certificate errors. It disables most security.

**Comment by mwarning** [comment]
I have implemented certificate import/pinning. So I am closing this now in favor of tickets reporting any errors.

**Comment by clach04** [comment]
Awesome! I'll look out for the next build release to test 👍

**Comment by clach04** [comment]
1.7.0 from Fdroid works great! :+1

**Comment by mwarning** [comment]
Great!
