### ISSUE TITLE
Automatically query status after changing status/polling/overview

### ISSUE THREAD

**Issue by Bixilon** [mwarning/trigger#58]
Thanks for the app, I am using it for years now, not for doors, but lamps: https://gitlab.bixilon.de/bixilon/zimmer-system

But I am missing some features:

 - Automatic polling when selected one "door"
 - Auto fetch status without pinging when "unlocking" or "locking".
 - Make an overview for all "doors" like a grid

What do you think about this? Are you interested in implementing it? I'd appreciate it

Thanks

Moritz

**Comment by mwarning** [comment]
Hi Bixilon,

thank you for your nice words and sorry for me breaking things from time to time. XD

>     * Automatic polling when selected one "door"
You mean to get the status every X seconds? That would not sound that valueable, because you usually do not have the app open for a longer period of time.
You open or bring the app into the foreground (the status then gets updated) and then you click open/close (which also updates the status) and then close the app or put it into the background again. A regular polling for the status is not needed fo that usecase.

>     * Auto fetch status without pinging when "unlocking" or "locking".
You need to help me here. How does it differ from the automatic polling?

>     * Make an overview for all "doors" like a grid
That sounds nice to have. But I do not feel motivated to implement this and have only very limited time available.
